[project]
name = "gaze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "shapely>=2.1.1",
    "tqdm>=4.67.1",
    "helper",
    "matplotlib>=3.10.8",
    "pupil-apriltags>=1.0.4.post11",
    "opencv-python>=4.13.0.90",
]

[tool.uv.sources]
helper = { path = "../../helper" }
